### PR TITLE
bump hie-bios

### PR DESCRIPTION
**Pull request by reactormonk**
An update ran today.

### CODE REVIEW

**Comment by infinisil** [comment]
Why is this necessary? https://github.com/reactormonk/haskell-ide-engine/commit/dc4e1464a52df3d8ce560abf84f51cd401c94c5e

Or what's the error without it? Also the nixpkgs version shouldn't be changed ideally

**Comment by reactormonk** [comment]
Because otherwise HaRe won't compile.

I dunno about the nixpkgs version, I just ran the update script.

**Comment by infinisil** [comment]
Ah sorry, the nixpkgs version wasn't changed, ignore that I said that.

What's the error for HaRe?

**Comment by reactormonk** [comment]
Needs a `ghc-exactprint >= 0.6`.

**Comment by infinisil** [comment]
Sorry for the delay, I'll look into it soonish, maybe an override in https://github.com/Infinisil/all-hies/tree/master/overrides is needed, but it might get complicated because those overrides are shared with the stable versions

**Comment by infinisil** [comment]
I just updated the hie-bios version in b4e60160c94e2bb38abf110ba829372af3037c8a, no special override seems to be needed with it (tested 8.6.4 and 8.6.5)

**Pull request closed without merging**
