### PR TITLE
Update hie bios versions

### PR DESCRIPTION
**Pull request by expipiplus1**
I'm not able to test all the versions sadly. Not sure how important that is for merging...

### CODE REVIEW

**Comment by infinisil** [comment]
From https://github.com/Infinisil/all-hies/issues/27#issuecomment-541815814 it seems that there could be problems with it. But it's not a stable version anyways, will take a look at it at some later time.

**Comment by infinisil** [comment]
Can you remove the `nix-store -r` command for hie-bios in the Readme? Then this looks good

**Comment by expipiplus1** [comment]
Done

FWIW this seems to work well in my basic testing for 865

**Review by infinisil — APPROVED** [review]
Awesome, that's nice to know, thanks!

**Pull request merged**
